export const SET_MESSAGE = "SET_MESSAGE";
export const SET_MESSAGE_RANDOM = "SET_MESSAGE_RANDOM";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const CLEAR_MESSAGE_RANDOM = "CLEAR_MESSAGE_RANDOM";

